# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: florientakoudad <florientakoudad@studen    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/10/14 22:54:43 by florientako       #+#    #+#              #
#    Updated: 2018/10/15 10:46:44 by florientako      ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do.op

SRC =	do_op.c \
		basic_fonc.c

OBJ = 	do_op.o \
		basic_fonc.o

FLAGS = -Wall -Werror -Wextra

all : $(NAME)

$(NAME) :
	 gcc -o do_op $(FLAGS) $(SRC)

clean :
	rm -f do_op